### ISSUE TITLE
Add to Slack button

### ISSUE THREAD

**Issue by casche** [mchairs/bot#3]

**Comment by thojansen** [comment]
https://api.slack.com/docs/slack-apps-checklist

**Comment by casche** [comment]
you can now add to slack with #12

**Comment by thojansen** [comment]
<a href="https://slack.com/oauth/authorize?scope=bot,incoming-webhook,team:read,users:read,channels:read,im:read,im:write,groups:read,chat:write:bot&client_id=21296122626.21890651699">
    <img alt="Add to Slack" height="40" width="139" src="https://platform.slack-edge.com/img/add_to_slack.png" ></a>

``` html
<a href="https://slack.com/oauth/authorize?scope=bot,incoming-webhook,team:read,users:read,channels:read,im:read,im:write,groups:read,chat:write:bot&client_id=21296122626.21890651699">
    <img alt="Add to Slack" height="40" width="139" src="https://platform.slack-edge.com/img/add_to_slack.png" 
        srcset="https://platform.slack-edge.com/img/add_to_slack.png 1x, https://platform.slack-edge.com/img/add_to_slack@2x.png 2x">
    </a>
```
